**Estelle Doriot**

_NSI 1ère_

---

# Exercices : Dictionnaires

---


### Exercice n°1

On donne le dictionnaire suivant :

```python
turing = {'nom':'Turing', 'prenoms':('Alan','Mathison'), 'nationalite':'anglaise', 'naissance' : 1912, 'mort':1954}
```

1. Afficher les prénoms de Turing.


In [1]:
turing = {
    "nom": "Turing",
    "prenoms": ("Alan", "Mathison"),
    "nationalite": "anglaise",
    "naissance": 1912,
    "mort": 1954,
}

print(turing["prenoms"])

('Alan', 'Mathison')


2. Afficher sa nationalité.


In [2]:
print(turing["nationalite"])

anglaise


3. Déterminer l'âge qu'avait Alan Turing à sa mort.


In [3]:
print(turing["mort"] - turing["naissance"])

42


### Exercice n°2

Le personnage d'un jeu vidéo possède dans un sac un ensemble d'objets, chacun possédant un poids en kilogramme. Cet ensemble est modélisé par le dictionnaire `sac`. On suppose qu'à un moment donné, le personnage possède le sac suivant : `sac = {"potion":0.01, "pain":1, "couverture":2, "couteau":0.2, "or":0.1}`.

1. Quel code Python permet de savoir la masse d'or présente dans le sac ?


In [4]:
sac = {"potion": 0.01, "pain": 1, "couverture": 2, "couteau": 0.2, "or": 0.1}

print(sac["or"])

0.1


2. Le personnage trouve un cristal de roche pesant 300 grammes, cristal qu'il décide de stocker dans son sac. Modifier le sac `sac` en conséquence.


In [5]:
sac["cristal"] = 0.3

print(sac)

{'potion': 0.01, 'pain': 1, 'couverture': 2, 'couteau': 0.2, 'or': 0.1, 'cristal': 0.3}


3. Ayant faim, le personnage mange 400 grammes de pain extrait de son sac. Modifier le sac `sac` en conséquence.


In [6]:
sac["pain"] -= 0.4

print(sac)

{'potion': 0.01, 'pain': 0.6, 'couverture': 2, 'couteau': 0.2, 'or': 0.1, 'cristal': 0.3}


4. Combien d'objets différents contient le sac du personnage finalement ?


In [7]:
print(len(sac))


6


### Exercice n°3

L'ensemble des moyennes obtenues lors d'un trimestre par Bob apparaissent dans le dictionnaire suivant :

```python
moyennes = {"nsi":18, "maths":17, "svt":14, "français":14, "lv1":8, "physique":12 ,"HG":11}
```

Déterminer la moyenne de Bob en créant une fonction `moy(notes:dict) -> float` qui prend en paramètre un dictionnaire `notes` dont les valeurs sont des nombres et qui renvoie la moyenne de ces nombres.


In [8]:
def moy(notes: dict) -> float:
    """calcule la moyenne générale d'un élève dont les moyennes par matière sont données dans un dictionnaire

    Args:
        notes (dict): un dictionnaire qui donne les moyennes obtenues pour chaque matière

    Returns:
        float: la moyenne générale des notes de notes
    """
    assert len(notes) != 0

    total = 0
    for value in notes.values():
        total += value
    return total / len(notes)


moyennes = {
    "nsi": 18,
    "maths": 17,
    "svt": 14,
    "français": 14,
    "lv1": 8,
    "physique": 12,
    "HG": 11,
}
print(moy(moyennes))

13.428571428571429


### Exercice n°4

Pour rappel, la fonction `ord(lettre)` donne le point de code unicde d'un caractère et `chr(pt)` donne le caractère associé au point de code `pt`. Créer un dictionnaire `alphabet` qui donne le point de code de chaque lettre majuscule.


In [9]:
alphabet = {chr(i): i for i in range(ord("A"), ord("Z") + 1)}
print(alphabet)

{'A': 65, 'B': 66, 'C': 67, 'D': 68, 'E': 69, 'F': 70, 'G': 71, 'H': 72, 'I': 73, 'J': 74, 'K': 75, 'L': 76, 'M': 77, 'N': 78, 'O': 79, 'P': 80, 'Q': 81, 'R': 82, 'S': 83, 'T': 84, 'U': 85, 'V': 86, 'W': 87, 'X': 88, 'Y': 89, 'Z': 90}


### Exercice n°5

Monsieur Germain prépare sa liste de course avant d'aller faire ses courses pour être sûr de ne pas dépasser son budget. Pour cela, il vérifie les prix de chaque article dans un catalogue.

Écrire une fonction `calcul_prix(produits:dict, catalogue:dict) -> float` où :

- `produits` est un dictionnaire contenant, comme clés, les produits souhaités par Monsieur Germain et comme valeurs associées, la quantité désirée de chacun d’entre eux,
- `catalogue` est un dictionnaire contenant tous les produits du magasin avec leur prix associé.

La fonction retourne le montant total des achats de Monsieur Germain.

L’appel suivant de la fonction :

```python
calcul_prix({"brocoli":2, "mouchoirs":5, "bouteilles d'eau":6},
            {"brocoli":1.50, "bouteilles d'eau":1, "bière":2,
             "savon":2.50, "mouchoirs":0.80})
```

doit retourner : `13.0`


In [10]:
def calcul_prix(produits: dict, catalogue: dict) -> float:
    """calcul le prix des courses

    Args:
        produits (dict): les produits que veut acheter Monsieur Germain avec leur quantité
        catalogue (dict): les produits disponibles avec le prix de chaque produit

    Returns:
        float: le prix total des courses de Monsieur Germain
    """
    total = 0
    for objet, qté in produits.items():
        total += qté * catalogue[objet]
    return total


assert (
    calcul_prix(
        {"brocoli": 2, "mouchoirs": 5, "bouteilles d'eau": 6},
        {
            "brocoli": 1.50,
            "bouteilles d'eau": 1,
            "bière": 2,
            "savon": 2.50,
            "mouchoirs": 0.80,
        },
    )
    == 13.0
)

### Exercice n°6

Écrire une fonction `extremes(nombres:list) -> dict` qui prend en paramètre une liste `nombres` de nombres a priori non triés, et qui renvoie la plus petite ainsi que la plus grande valeur de la liste sous la forme d'un dictionnaire à deux clés 'min' et 'max'. Si la liste est vide, les extrêmes n'existent pas ; on utilisera alors `None` pour chacun. On n'utilisera pas les fonctions `min` et `max` fournies par le langage.


In [11]:
def extremes(nombres: list) -> dict:
    """détermine le minimum et le maximum des valeurs d'une liste

    Args:
        nombres (list): une liste de nombres

    Returns:
        dict: dictionnaire contenant le minimum et le maximum des valeurs de nombres
    """
    min_max = {"min": None, "max": None}
    for n in nombres:
        if min_max["min"] is None or n < min_max["min"]:
            min_max["min"] = n
        if min_max["max"] is None or n > min_max["max"]:
            min_max["max"] = n
    return min_max


assert extremes([0, 1, 4, 2, -2, 9, 3, 1, 7, 1]) == {"min": -2, "max": 9}
assert extremes([37, 37]) == {"min": 37, "max": 37}
assert extremes([]) == {"min": None, "max": None}

### Exercice n°7

Une couleur en HTML est représentée par une chaine de caractères de sept caractères dont le premier est `'#'` ; les six autres, groupés 2 par 2 forment 3 entiers en hexadécimal (base 16). Le premier entier est la quantité de rouge ; le deuxième la quantité de vert et le troisième est la quantité de bleu. Ces trois valeurs hexadécimales sont comprises entre `"00"` et `"FF"`.

Une autre façon de représenter une couleur est par un triplet $(r, v, b)$ de valeurs décimales comprises entre 0 et 255 : $r$ est la quantité de rouge, $v$ la quantité de vert et $b$ la quantité de bleu.

On souhaite écrire une fonction `html_vers_rvb(html:str) -> tuple` qui prend une chaine de caractères représentant une couleur HTML en paramètre et qui renvoie le triplet de décimaux $(r, v, b)$ représentant la même couleur.

On rappelle les valeurs décimales des 16 chiffres hexadécimaux sont : '0' vaut $0$, jusqu'à '9' qui vaut $9$, puis 'A' vaut $10$, 'B' vaut $11$ ainsi de suite jusqu'à 'F' qui vaut $15$.

1. Compléter le dictionnaire `HEX_DEC` qui donne les valeurs décimales des chiffres hexadécimaux.


In [12]:
HEX_DEC = {
    "0": 0,
    "1": 1,
    "2": 2,
    "3": 3,
    "4": 4,
    "5": 5,
    "6": 6,
    "7": 7,
    "8": 8,
    "9": 9,
    "A": 10,
    "B": 11,
    "C": 12,
    "D": 13,
    "E": 14,
    "F": 15,
}

2. Écrire la définition de la fonction `hex_int(a:str, b:str) -> int` qui prend deux chaines d'un caractère en paramètres `a` et `b` ; de sorte que $(ab)_{16}$ est un entier en hexadécimal et renvoie la valeur décimale associée.


In [13]:
def hex_int(a: str, b: str) -> int:
    """convertit un nombre hexadécimal en décimal

    Args:
        a (str): chiffre des seizaines en hexadécimal
        b (str): chiffre des unités en hexadécimal

    Returns:
        int: (ab)_16 converti en décimal
    """
    return HEX_DEC[a] * 16 + HEX_DEC[b]


assert hex_int("B", "5") == 181
assert hex_int("0", "0") == 0

3. Écrire la définition de la fonction `html_vers_rvb(html:str) -> tuple` en vous servant de la fonction précédente.


In [14]:
def html_vers_rvb(html: str) -> tuple:
    """convertit une couleur en HTML en RVB

    Args:
        html (str): couleur en HTML

    Returns:
        tuple: couleur en RVB
    """
    return (
        hex_int(html[1], html[2]),
        hex_int(html[3], html[4]),
        hex_int(html[5], html[6]),
    )


assert html_vers_rvb("#C0392B") == (192, 57, 43)
assert html_vers_rvb("#00FF00") == (0, 255, 0)
assert html_vers_rvb("#000000") == (0, 0, 0)

### Exercice n°8 : Anagramme

1. Pour compter le nombre de fois que chaque caractère apparaît dans une phrase, écrire une fonction `occurrence_caracteres(phrase:str) -> dict` qui prend en paramètre une chaîne de caractères `phrase` et qui renvoie un dictionnaire dont les clés sont les caractères présents dans `phrase` et les valeurs sont le nombre de fois que ce caractère est présent dans `phrase`.


In [15]:
def occurrence_caracteres(phrase: str) -> dict:
    """calcule le nombre d'occurrence de chaque caractère d'une phrase

    Args:
        phrase (str): une phrase

    Returns:
        dict: nombre d'occurrence de chaque caractère de phrase
    """
    d = {}
    for c in phrase:
        if c not in d:
            d[c] = 1
        else:
            d[c] += 1
    return d


assert occurrence_caracteres("Bonjour à tous !") == {
    "B": 1,
    "o": 3,
    "n": 1,
    "j": 1,
    "u": 2,
    "r": 1,
    " ": 3,
    "à": 1,
    "t": 1,
    "s": 1,
    "!": 1,
}
assert occurrence_caracteres("ababbab") == {"a": 3, "b": 4}

2. Une anagramme est un mot ou une expression obtenu en permutant les lettres d'un mot ou d'une expression de départ. Par exemple, "gare" est une anagramme de "rage". Ecrire une fonction `anagramme(mot1:str, mot2:str) -> bool` qui renvoie `True` si `mot1` est une anagramme de `mot2`. On pourra réutiliser la fonction écrite à la question précédente.


In [16]:
def anagramme(mot1: str, mot2: str) -> bool:
    """détermine si deux mots sont des anagrammes l'un de l'autre

    Args:
        mot1 (str): un mot
        mot2 (str): un mot

    Returns:
        bool: True si mot1 est une anagramme de mot2
    """
    return occurrence_caracteres(mot1) == occurrence_caracteres(mot2)


assert anagramme("gare", "rage")

### Exercice n°9

La fréquence d'apparition d'une lettre dans un texte ou une phrase est le pourcentage
donné selon la formule :

$\text{fréquence d'apparition d'une lettre} = \frac{\text{nombre d'occurrences de la lettre} \times 100}{\text{nombre total de lettres}}$

Par exemple, la phrase ESPRIT ES TU LA contient 12 lettres; la lettre E y apparaît 2 fois. La fréquence d'apparition de E dans cette phrase est donc : $f = \frac{2 \times 100}{12} = 16.66$

1. Ecrire une fonction `frequence_lettres(message:str) -> dict` qui prend en argument une chaîne de caractères et qui renvoie un dictionnaire contenant les fréquences des lettres.


In [17]:
def frequence_lettres(message: str) -> dict:
    """caclcule la fréquence des lettres dans une chaîne de caractères

    Args:
        message (str): une chaine de caractères

    Returns:
        dict: dictionnaire des fréquences de lettres dans message
    """
    freq = {chr(i): 0 for i in range(ord("A"), ord("Z") + 1)}
    total = 0

    for lettre in message:
        if lettre != " ":
            total += 1
            freq[lettre] += 1

    return {key: freq[key] * 100 / total for key in freq}


print(frequence_lettres("ESPRIT ES TU LA"))

{'A': 8.333333333333334, 'B': 0.0, 'C': 0.0, 'D': 0.0, 'E': 16.666666666666668, 'F': 0.0, 'G': 0.0, 'H': 0.0, 'I': 8.333333333333334, 'J': 0.0, 'K': 0.0, 'L': 8.333333333333334, 'M': 0.0, 'N': 0.0, 'O': 0.0, 'P': 8.333333333333334, 'Q': 0.0, 'R': 8.333333333333334, 'S': 16.666666666666668, 'T': 16.666666666666668, 'U': 8.333333333333334, 'V': 0.0, 'W': 0.0, 'X': 0.0, 'Y': 0.0, 'Z': 0.0}


2. Voici la fréquence d'apparition des lettres selon la langue utilisée :

| Lettre | Anglais | Français | Allemand | Espagnol |
| ------ | ------- | -------- | -------- | -------- |
| a      | 8.167%  | 8.173%   | 7.094%   | 12.027%  |
| b      | 1.492%  | 0.901%   | 1.886%   | 2.215%   |
| c      | 2.782%  | 3.345%   | 2.732%   | 4.019%   |
| d      | 4.253%  | 3.669%   | 5.076%   | 5.010%   |
| e      | 12.702% | 16.734%  | 16.396%  | 12.614%  |
| f      | 2.228%  | 1.066%   | 1.656%   | 0.692%   |
| g      | 2.015%  | 0.866%   | 3.009%   | 1.768%   |
| h      | 6.094%  | 0.737%   | 4.577%   |  0.703%  |
| i      | 6.966%  | 7.579%   | 6.550%   | 6.972%   |
| j      | 0.153%  | 0.613%   | 0.268%   | 0.493%   |
| k      | 0.772%  | 0.049%   | 1.417%   | 0.011%   |
| l      | 4.025%  | 5.456%   | 3.437%   | 4.967%   |
| m      | 2.406%  | 2.968%   | 2.534%   | 3.157%   |
| n      | 6.749%  | 7.095%   | 9.776%   | 7.023%   |
| o      | 7.507%  | 5.819%   | 3.037%   | 9.510%   |
| p      | 1.929%  | 2.521%   | 0.670%   | 2.510%   |
| q      | 0.095%  | 1.362%   | 0.018%   | 0.877%   |
| r      | 5.987%  | 6.693%   | 7.003%   | 6.871%   |
| s      | 6.327%  | 7.948%   | 7.577%   | 7.977%   |
| t      | 9.056%  | 7.244%   | 6.154%   | 4.632%   |
| u      | 2.758%  | 6.429%   | 5.161%   | 3.107%   |
| v      | 0.978%  | 1.838%   | 0.846%   | 1.138%   |
| w      | 2.360%  | 0.074%   | 1.921%   | 0.017%   |
| x      | 0.150%  | 0.427%   | 0.034%   | 0.215%   |
| y      | 1.974%  | 0.128%   | 0.039%   | 1.008%   |
| z      | 0.074%  | 0.326%   | 1.134%   | 0.467%   |

Dans quelles langues ont été écrits les quatre textes suivants (les lettres de
chaque mot ont été mélangées).

```python
texte1 = "TMAIER BERACUO RSU NU REBRA PRCEEH EIANTT NE ONS EBC NU GAOFREM EIMATR RERNAD APR L RDUOE LAHECLE UILTTNI A EUP SREP EC LGNGAEA TE RBONUJO ERMNOUSI DU UBRACEO QUE OVSU EEST LIJO UOE OUVS EM MSZELBE BAEU ASNS MIERNT IS RVETO AGRAME ES PRARPTOEA OEVTR AMGUPLE VUOS SEET EL PNIHXE DSE OSHET ED CSE BIOS A ESC MSOT LE OUBRCEA NE ES ESTN ASP DE IEJO TE OUPR ERRNOTM AS BELEL XOVI IL, OREVU NU RGLEA ECB ILESSA EBOMTR AS PIOER EL NRDAER S EN ISIAST TE ITD MNO NOB EUSRMNOI NRPEEAZP QEU UTOT EUTLRETA IVT XUA SPNEDE DE UECIL UOI L TECEOU TECET NEOCLVATU BNEI UN GMAEORF SNAS TUOED LE EOABURC OHENTXU TE NSCOFU UJRA SMIA UN EPU TRDA UO NO EN L Y ARRPEIDNT ULSP"

texte2 = "WRE TREITE SO TSPA CUDHR AHNCT UND WIND SE STI RED AEVRT M'TI ESEIMN IDNK RE ATH END NEABNK WLOH NI EMD AMR ER AFTSS HIN IHSERC RE AHTL HIN MRWA EINM SHNO SAW SRTIBG UD SONGBA DNEI EIHSGTC ESISTH RAETV UD DEN LERNIOKG NITHC NDE LOENINKGRE TIM OKRN UDN CHWFSEI NEIM NSOH ES STI IEN BIFTRISEEEN DU BILESE IKDN OMKM EHG MIT MIR RAG ECHNOS EPELSI EIPSL IHC ITM RDI HNCMA BEUTN MBLUNE DINS NA DEM TNDRAS NMIEE UTETMMR AHT CAMHN UDNGEL GDAWEN MIEN EATRV MENI VEART DUN OSTHER DU CINTH SAW KNNOEIREGL RIM ILEES PRSTVRCIEH ISE IHGRU BEEILB RIGUH MNEI KNDI NI RDNEUR NATBRLET STAESUL EDR WNID"

texte3 = "DSNOACAIF ORP ANU DAEDALRI DNAAEIMTI EQU NNCOSETE EL RSTEOUL SMA AACTFAITMNS UOE LE TSVAO OINSRVUE DEU S ANIGIICANOM EIORDP TOOD RTEIENS RPO LE ITOABOLRROA ED OIUAMALI USOP A NSSRCAEADLA TMREAAINXTADAUEE ROP GOARLS EMESS DE NNAMICLUIAPO Y LOVOIV A RES LE RHMEOB EOMDNEERPRD DE LOS RSOPMRIE OMTSIPE UEQ CUIDADE LE RTDAAOZ ED LSA CELSAL Y LA NICOIOPS ED LAS UESVNA SSACA Y ES ITRMNEEOD QEU AERFU EL UEQIN IIIRDEGAR LA. NAIORTREICP DE AL RRTEIA"

texte4 = "IMTRUESMME DNA TEH LNGIIV SI EYAS SIFH REA GJPNUIM DNA HET TTNOCO IS GHIH OH OUYR DDADY SI IRHC DAN ROUY MA SI DOGO GKOILON OS USHH LTLIET BBYA NDOT OUY CYR NEO OF HESET GNSRONIM YUO RE NANGO SIER PU SNIGING NAD OULLY EPADRS YUOR GINSW DAN LYOLU KATE OT HET KSY TUB ITLL TATH MGNIRNO EREHT NATI INTGOHN ACN AHMR OYU TWIH DADYD NDA MYMMA NSTIDGAN YB"
```


In [18]:
freq_en = {
    "A": 8.167,
    "B": 1.492,
    "C": 2.782,
    "D": 4.253,
    "E": 12.702,
    "F": 2.228,
    "G": 2.015,
    "H": 6.094,
    "I": 6.966,
    "J": 0.153,
    "K": 0.772,
    "L": 4.025,
    "M": 2.406,
    "N": 6.749,
    "O": 7.507,
    "P": 1.929,
    "Q": 0.095,
    "R": 5.987,
    "S": 6.327,
    "T": 9.056,
    "U": 2.758,
    "V": 0.978,
    "W": 2.360,
    "X": 0.150,
    "Y": 1.974,
    "Z": 0.074,
}

freq_fr = {
    "A": 8.173,
    "B": 0.901,
    "C": 3.345,
    "D": 3.669,
    "E": 16.734,
    "F": 1.066,
    "G": 0.866,
    "H": 0.737,
    "I": 7.579,
    "J": 0.613,
    "K": 0.049,
    "L": 5.456,
    "M": 2.968,
    "N": 7.095,
    "O": 5.819,
    "P": 2.521,
    "Q": 1.362,
    "R": 6.693,
    "S": 7.948,
    "T": 7.244,
    "U": 6.429,
    "V": 1.838,
    "W": 0.074,
    "X": 0.427,
    "Y": 0.128,
    "Z": 0.326,
}

freq_de = {
    "A": 7.094,
    "B": 1.886,
    "C": 2.732,
    "D": 5.076,
    "E": 16.396,
    "F": 1.656,
    "G": 3.009,
    "H": 4.577,
    "I": 6.550,
    "J": 0.268,
    "K": 1.417,
    "L": 3.437,
    "M": 2.534,
    "N": 9.776,
    "O": 3.037,
    "P": 0.670,
    "Q": 0.018,
    "R": 7.003,
    "S": 7.577,
    "T": 6.154,
    "U": 5.161,
    "V": 0.846,
    "W": 1.921,
    "X": 0.034,
    "Y": 0.039,
    "Z": 1.134,
}

freq_es = {
    "A": 12.027,
    "B": 2.215,
    "C": 4.019,
    "D": 5.010,
    "E": 12.614,
    "F": 0.692,
    "G": 1.768,
    "H": 0.703,
    "I": 6.972,
    "J": 0.493,
    "K": 0.011,
    "L": 4.967,
    "M": 3.157,
    "N": 7.023,
    "O": 9.510,
    "P": 2.510,
    "Q": 0.877,
    "R": 6.871,
    "S": 7.977,
    "T": 4.632,
    "U": 3.107,
    "V": 1.138,
    "W": 0.017,
    "X": 0.215,
    "Y": 1.008,
    "Z": 0.467,
}


def distance2(dico1: dict, dico2: dict) -> float:
    """calcule la distance au carré entre deux distributions de fréquences de lettres

    Args:
        dico1 (dict): une distribution de fréquence de lettres
        dico2 (dict): une distribution de fréquence de lettres

    Returns:
        float: distance entre les distributions dico1 et dico2
    """
    alphabet = "ABSCDEFGHIJKLMNOPQRSTUVWXYZ"
    dist2 = 0
    for lettre in alphabet:
        dist2 += (dico1[lettre] - dico2[lettre]) ** 2
    return dist2


texte1 = "TMAIER BERACUO RSU NU REBRA PRCEEH EIANTT NE ONS EBC NU GAOFREM EIMATR RERNAD APR L RDUOE LAHECLE UILTTNI A EUP SREP EC LGNGAEA TE RBONUJO ERMNOUSI DU UBRACEO QUE OVSU EEST LIJO UOE OUVS EM MSZELBE BAEU A S N SMIERNT IS R E T O AGRAME ES PRARPTOEA OEVTR AMGUPLE VUOS SEET EL PNIHXE DSE OSHET ED CSE BIOS A ESC MSOT LE OUBRCEA NE ES ESTN ASP DE IEJO TE OUPR ERRNOTM AS BELEL XOVI IL OREVU NU RGLEA ECB ILESSA EBOMTR AS PIOER EL NRDAER S EN ISIAST TE ITD MNO NOB EUSRMNOI NRPEEAZP QEU UTOT EUTLRETA IVT XUA SPNEDE DE UECIL UOI L TECEOU TECET NEOCLVATU BNEI UN GMAEORF SNAS TUOED LE EOABURC OHENTXU TE NSCOFU UJRA SMIA UN EPU TRDA UO NO EN L Y ARRPEIDNT ULSP"

texte2 = "WRE TREITE SO TSPA CUDHR AHNCT UND WIND SE STI RED AEVRT MTI ESEIMN IDNK RE ATH END NEABNK WLOH NI EMD AMR ER AFTSS HIN IHSERC RE AHTL HIN MRWA EINM SHNO SAW SRTIBG UD SONGBA DNEI EIHSGTC ESISTH RAETV UD DEN LERNIOKG NITHC NDE LOENINKGRE TIM OKRN UDN CHWFSEI NEIM NSOH ES STI IEN BIFTRISEEEN DU BILESE IKDN OMKM EHG MIT MIR RAG ECHNOS EPELSI EIPSL IHC ITM RDI HNCMA BEUTN MBLUNE DINS NA DEM TNDRAS NMIEE UTETMMR AHT CAMHN UDNGEL GDAWEN MIEN EATRV MENI VEART DUN OSTHER DU CINTH SAW KNNOEIREGL RIM ILEES PRSTVRCIEH ISE IHGRU BEEILB RIGUH MNEI KNDI NI RDNEUR NATBRLET STAESUL EDR WNID"

texte3 = "DSNOACAIF ORP ANU DAEDALRI DNAAEIMTI EQU NNCOSETE EL RSTEOUL SMA AACTFAITMNS UOE LE TSVAO OINSRVUE DEU S ANIGIICANOM EIORDP TOOD RTEIENS RPO LE ITOABOLRROA ED OIUAMALI USOP A NSSRCAEADLA TMREAAINXTADAUEE ROP GOARLS EMESS DE NNAMICLUIAPO Y LOVOIV A RES LE RHMEOB EOMDNEERPRD DE LOS RSOPMRIE OMTSIPE UEQ CUIDADE LE RTDAAOZ ED LSA CELSAL Y LA NICOIOPS ED LAS UESVNA SSACA Y ES ITRMNEEOD QEU AERFU EL UEQIN IIIRDEGAR LA NAIORTREICP DE AL RRTEIA"

texte4 = "IMTRUESMME DNA TEH LNGIIV SI EYAS SIFH REA GJPNUIM DNA HET TTNOCO IS GHIH OH OUYR DDADY SI IRHC DAN ROUY MA SI DOGO GKOILON OS USHH LTLIET BBYA NDOT OUY CYR NEO OF HESET GNSRONIM YUO RE NANGO SIER PU SNIGING NAD OULLY EPADRS YUOR GINSW DAN LYOLU KATE OT HET KSY TUB ITLL TATH MGNIRNO EREHT NATI INTGOHN ACN AHMR OYU TWIH DADYD NDA MYMMA NSTIDGAN YB"


def recherche_langue(texte: str) -> str:
    """recherche la langue dans laquelle est écrite un texte donné en paramètre

    Args:
        texte (str): un texte

    Returns:
        str: la langue du texte
    """
    freq = frequence_lettres(texte)
    distances = {
        "anglais": distance2(freq, freq_en),
        "français": distance2(freq, freq_fr),
        "allemand": distance2(freq, freq_de),
        "espagnol": distance2(freq, freq_es),
    }
    langue = "anglais"
    distance = distances["anglais"]
    for clé, valeur in distances.items():
        if valeur < distance:
            langue = clé
            distance = valeur
    return langue


print(recherche_langue(texte1))
print(recherche_langue(texte2))
print(recherche_langue(texte3))
print(recherche_langue(texte4))

français
allemand
espagnol
anglais


### Exercice n°10 : Bataille

Dans un jeu de cartes de 54 cartes, les cartes sont organisées en 4 couleurs : pique, coeur, carreau, trèfle. On considère que la valeur d'une carte correspond à 2 si c'est un deux, 3 si c'est un trois, ..., 10 pour un dix, 11 pour un valet, 12 pour une dame, 13 pour un roi et 14 pour un as.

1. Créer un dictionnaire nommé `valeur_carte` dont les clés sont les noms des cartes (2,3,...,10 , valet, Dame, Roi, As) et les valeurs les valeurs de ces clés. Par exemple votre dictionnaire devra renvoyer :

```python
>>> valeur_carte['valet']
11
```


In [19]:
liste_cartes = [2, 3, 4, 5, 6, 7, 8, 9, 10, "valet", "dame", "roi", "as"]
valeur_carte = {liste_cartes[i]: i + 2 for i in range(len(liste_cartes))}
print(valeur_carte)

{2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8: 8, 9: 9, 10: 10, 'valet': 11, 'dame': 12, 'roi': 13, 'as': 14}


2. Créer un dictionnaire nommé `jeu_carte` dont :
   - les clés sont les 52 tuples (nom, couleur) des cartes d'un jeu de 52 cartes : ('2','pique') , ... ,('as','pique'), ('2','coeur'), ... ,('as','coeur')...
   - et les valeurs, les valeurs de ces cartes (clés).

Par exemple votre dictionnaire devra renvoyer :

```python
>>> jeu_carte[('dame','pique')]
12
```


In [20]:
couleurs = ("♠", "♥", "♦", "♣")
jeu_carte = {
    (nom, couleur): valeur
    for nom, valeur in valeur_carte.items()
    for couleur in couleurs
}
print(jeu_carte)

{(2, '♠'): 2, (2, '♥'): 2, (2, '♦'): 2, (2, '♣'): 2, (3, '♠'): 3, (3, '♥'): 3, (3, '♦'): 3, (3, '♣'): 3, (4, '♠'): 4, (4, '♥'): 4, (4, '♦'): 4, (4, '♣'): 4, (5, '♠'): 5, (5, '♥'): 5, (5, '♦'): 5, (5, '♣'): 5, (6, '♠'): 6, (6, '♥'): 6, (6, '♦'): 6, (6, '♣'): 6, (7, '♠'): 7, (7, '♥'): 7, (7, '♦'): 7, (7, '♣'): 7, (8, '♠'): 8, (8, '♥'): 8, (8, '♦'): 8, (8, '♣'): 8, (9, '♠'): 9, (9, '♥'): 9, (9, '♦'): 9, (9, '♣'): 9, (10, '♠'): 10, (10, '♥'): 10, (10, '♦'): 10, (10, '♣'): 10, ('valet', '♠'): 11, ('valet', '♥'): 11, ('valet', '♦'): 11, ('valet', '♣'): 11, ('dame', '♠'): 12, ('dame', '♥'): 12, ('dame', '♦'): 12, ('dame', '♣'): 12, ('roi', '♠'): 13, ('roi', '♥'): 13, ('roi', '♦'): 13, ('roi', '♣'): 13, ('as', '♠'): 14, ('as', '♥'): 14, ('as', '♦'): 14, ('as', '♣'): 14}


3. Créer une fonction `bataille(jeu_cartes:dict)` qui va choisir au hasard deux cartes distinctes du jeu, les afficher, comparer leur valeurs et donner la carte gagnante ou le cas d'égalité. On pourra utiliser la fonction `sample(liste, nb)` du module `random` qui choisit `nb` cartes au hasard dans la liste `liste`.


In [21]:
from random import sample


def bataille(jeu_cartes: dict) -> None:
    """joue une bataille entre deux cartes tirées au hasard et affiche la carte gagnante ou l'égalité le cas échéant

    Args:
        jeu_cartes (dict): un jeu de carte sous forme de dictionnaire où les clés sont des cartes au format (nombre, couleur) et les valeurs sont les valeurs de la carte à la bataille
    """
    tirées = sample(list(jeu_cartes.keys()), 2)
    print(f"Le joueur 1 a tiré la carte {tirées[0]}.")
    print(f"Le joueur 2 a tiré la carte {tirées[1]}.")
    if jeu_cartes[tirées[0]] == jeu_cartes[tirées[1]]:
        print("Egalité")
    elif jeu_cartes[tirées[0]] > jeu_cartes[tirées[1]]:
        print("Le joueur 1 gagne")
    else:
        print("Le joueur 2 gagne")


bataille(jeu_carte)

Le joueur 1 a tiré la carte ('as', '♣').
Le joueur 2 a tiré la carte ('roi', '♣').
Le joueur 1 gagne


### Exercice n°11 : Photos

Lors de la prise d’une photo avec un appareil photo, des **métadonnées** sont encodés dans le fichier généré (au format compressé JPEG dans de nombreux cas) selon le standard EXIF.
Ce standard regroupe un ensemble de clés décrivant des informations sur la photo telles que, par exemple :

- la date et l’heure de prise de vue ;
- le fabricant et le modèle de l’appareil ;
- les dimensions (largeur / hauteur) ;
- la résolution (horizontale / verticale) ;
- la longueur de focale et autres informations techniques (valeur d’ouverture, flash, etc) ;
- le lieu de prise de vue lorsque l’appareil dispose d’un système de localisation.

Les valeurs associées à ces clés peuvent être de différents types (entier, séquence de bits, chaîne de caractère voire dictionnaire). Selon les appareils, toutes les valeurs ne sont pas nécessairement renseignées lors de l’écriture des métadonnées.

En python, le module `PIL` fournit des méthodes qui permettent de récupérer les données EXIF d’une photo sous la forme d’un dictionnaire.

1. a. Importer la photo `image_mystere.jpg` et afficher ses données EXIF en utilisant la méthode `_getexif()` grâce au code ci-dessous:

```python
import PIL.Image # importation du module Image de PIL

img = PIL.Image.open("image_mystere.jpg") # ouverture du fichier jpg
exif_dico = img._getexif() # récupération des données EXIF
```


In [22]:
import PIL.Image  # importation du module Image de PIL

img = PIL.Image.open("image_mystere.jpg")  # ouverture du fichier jpg
exif_dico = img._getexif()  # récupération des données EXIF


def affiche_dico(dico: dict) -> None:
    """affiche les métadonnées contenues dans un dictionnaire

    Args:
        dico (dict): un dictionnaire de métadonnées EXIF
    """
    for clé, valeur in dico.items():
        print(f"{clé:5} :\t{valeur}")


# affichage des données EXIF
print("\nDonnées EXIF :")
affiche_dico(exif_dico)


Données EXIF :
34853 :	{0: b'\x02\x02\x00\x00', 1: 'N', 2: (48.0, 50.4225, 0.0), 3: 'E', 4: (2.0, 18.899, 0.0), 6: 55.2454}
  296 :	2
34665 :	228
  271 :	NIKON CORPORATION
  272 :	NIKON D7200
  305 :	Adobe Photoshop Lightroom 6.8 (Windows)
  306 :	2017:02:06 03:10:48
  282 :	300.0
  283 :	300.0
36864 :	b'0230'
37377 :	8.965784
37378 :	3.851999
36867 :	2015:11:30 16:26:55
36868 :	2015:11:30 16:26:55
37380 :	-0.3333333333333333
37381 :	3.8
37383 :	2
37384 :	0
37385 :	16
37386 :	22.0
40961 :	1
41987 :	0
41988 :	1.0
41486 :	2558.6412048339844
41487 :	2558.6412048339844
41488 :	3
37521 :	65
37522 :	65
41994 :	0
41996 :	0
41495 :	2
41728 :	b'\x03'
33434 :	0.002
33437 :	3.8
41729 :	b'\x01'
34850 :	4
41730 :	b'\x02\x00\x02\x00\x00\x01\x01\x02'
41985 :	0
34855 :	1250
41986 :	0
34864 :	2
42033 :	4325319
42034 :	(18.0, 105.0, 3.5, 5.6)
42036 :	18.0-105.0 mm f/3.5-5.6
41989 :	33
41990 :	0
41991 :	2
41992 :	0
41993 :	0


b. Quel est le type des clés du dictionnaire `exif_dico` ?

Ce sont des entiers.


2. Les clés du dictionnaire exif_dico ne renseignent pas quant à la nature des métadonnées enregistrées. Le module `PIL` fournit alors un dictionnaire qui associe à certains de ces nombres entiers une chaîne de caractères « plus éloquente » (comme "ImageWidth", "DateTime", etc.)

   a. Recopier et exécuter le script ci-dessous.

```python
from PIL.ExifTags import TAGS
print(TAGS)
```


In [23]:
from PIL.ExifTags import TAGS

print("TAGS des données EXIF :")
affiche_dico(TAGS)


TAGS des données EXIF :
    1 :	InteropIndex
   11 :	ProcessingSoftware
  254 :	NewSubfileType
  255 :	SubfileType
  256 :	ImageWidth
  257 :	ImageLength
  258 :	BitsPerSample
  259 :	Compression
  262 :	PhotometricInterpretation
  263 :	Thresholding
  264 :	CellWidth
  265 :	CellLength
  266 :	FillOrder
  269 :	DocumentName
  270 :	ImageDescription
  271 :	Make
  272 :	Model
  273 :	StripOffsets
  274 :	Orientation
  277 :	SamplesPerPixel
  278 :	RowsPerStrip
  279 :	StripByteCounts
  280 :	MinSampleValue
  281 :	MaxSampleValue
  282 :	XResolution
  283 :	YResolution
  284 :	PlanarConfiguration
  285 :	PageName
  288 :	FreeOffsets
  289 :	FreeByteCounts
  290 :	GrayResponseUnit
  291 :	GrayResponseCurve
  292 :	T4Options
  293 :	T6Options
  296 :	ResolutionUnit
  297 :	PageNumber
  301 :	TransferFunction
  305 :	Software
  306 :	DateTime
  315 :	Artist
  316 :	HostComputer
  317 :	Predictor
  318 :	WhitePoint
  319 :	PrimaryChromaticities
  320 :	ColorMap
  321 :	HalftoneHints
  322 :

b. Dans le dictionnaire TAGS, quelle valeur est associée à la clé 306 ? Que représente-t-elle ?


In [24]:
print(TAGS[306])


DateTime


c. Même question pour les clés 36867 et 36868.


In [25]:
print(TAGS[36867])
print(TAGS[36868])


DateTimeOriginal
DateTimeDigitized


d. Écrire une fonction `get_original_time(f:str) -> str` qui prend en argument le nom d’une image au format JPEG et renvoie sa date de prise de vue.


In [26]:
def get_original_time(filename: str) -> str:
    """renvoie la date et l'heure d'une photo

    Args:
        filename (str): nom d'une image

    Returns:
        str: date et heure de la prise de vue
    """
    img = PIL.Image.open(filename)
    exif_dico = img._getexif()
    for clé, valeur in TAGS.items():
        if valeur == "DateTimeOriginal":
            return exif_dico[clé]
    return ""


assert get_original_time("image_mystere.jpg") == "2015:11:30 16:26:55"

3. On s’intéresse dans cette question aux données de localisation de la photo `image_mystere.jpg`.

   a. Quelle est la clé du dictionnaire `TAGS` dont la valeur est `GPSInfo` ?


In [27]:
gps = ""
for clé, valeur in TAGS.items():
    if valeur == "GPSInfo":
        gps = clé
        break

print(f"Clé TAGS correspondant à GPSInfo: {gps}")

Clé TAGS correspondant à GPSInfo: 34853


b. Quel est le type de la valeur associé à la clé précédente dans le dictionnaire `exif_dico` ?


In [28]:
affiche_dico(exif_dico[gps])


    0 :	b'\x02\x02\x00\x00'
    1 :	N
    2 :	(48.0, 50.4225, 0.0)
    3 :	E
    4 :	(2.0, 18.899, 0.0)
    6 :	55.2454


Il s'agit d'un dictionnaire.


c. Le module `PIL` fournit également un dictionnaire pour les données GPS. Recopier le code ci-dessous pour accéder aux tags GPS :

```python
from PIL.ExifTags import GPSTAGS
print(GPSTAGS)
```


In [29]:
from PIL.ExifTags import GPSTAGS

print("GPSTAGS:")
affiche_dico(GPSTAGS)


GPSTAGS:
    0 :	GPSVersionID
    1 :	GPSLatitudeRef
    2 :	GPSLatitude
    3 :	GPSLongitudeRef
    4 :	GPSLongitude
    5 :	GPSAltitudeRef
    6 :	GPSAltitude
    7 :	GPSTimeStamp
    8 :	GPSSatellites
    9 :	GPSStatus
   10 :	GPSMeasureMode
   11 :	GPSDOP
   12 :	GPSSpeedRef
   13 :	GPSSpeed
   14 :	GPSTrackRef
   15 :	GPSTrack
   16 :	GPSImgDirectionRef
   17 :	GPSImgDirection
   18 :	GPSMapDatum
   19 :	GPSDestLatitudeRef
   20 :	GPSDestLatitude
   21 :	GPSDestLongitudeRef
   22 :	GPSDestLongitude
   23 :	GPSDestBearingRef
   24 :	GPSDestBearing
   25 :	GPSDestDistanceRef
   26 :	GPSDestDistance
   27 :	GPSProcessingMethod
   28 :	GPSAreaInformation
   29 :	GPSDateStamp
   30 :	GPSDifferential
   31 :	GPSHPositioningError


d. Quelles sont les valeurs associées aux longitudes et latitudes du lieu où la photo a été prise ?


In [30]:
latitude = tuple()
longitude = tuple()

for clé, valeur in GPSTAGS.items():
    if valeur == "GPSLatitude":
        latitude = exif_dico[gps][clé]
    elif valeur == "GPSLongitude":
        longitude = exif_dico[gps][clé]

print(f"Latitude de la photo : {latitude}")
print(f"Longitude de la photo : {longitude}")

Latitude de la photo : (48.0, 50.4225, 0.0)
Longitude de la photo : (2.0, 18.899, 0.0)


e. Les coordonnées (longitudes et latitudes) sont des angles présentées sous la forme d’un triplet (d, m, s). La valeur en degrés de l’angle $\alpha$ ainsi représenté s’obtient par le calcul suivant $\alpha = d + \frac{m}{60} + \frac{s}{3600}$. Déterminer les coordonnées (longitudes, latitudes) du lieu où cette photo a été prise (on pourra vérifier avec un célèbre logiciel de cartographie en ligne).


In [31]:
latitude_degres = latitude[0] + latitude[1] / 60 + latitude[2] / 3600
longitude_degres = longitude[0] + longitude[1] / 60 + longitude[2] / 3600

print(f"Latitude de la photo (degres): {float(latitude_degres)}")
print(f"Longitude de la photo (degres): {float(longitude_degres)}")

Latitude de la photo (degres): 48.840375
Longitude de la photo (degres): 2.314983333333333


4. Écrire une fonction `donnees_exif(filename:str) -> dict` qui stocke les données EXIF d’une photo au format JPEG dans un dictionnaire dont les clés sont des chaînes de caractères « éloquentes » (à savoir les valeurs des dictionnaires TAGS et GPSTAGS).


In [32]:
def donnees_exif(filename: str) -> dict:
    """donne les données EXIF d'une photo avec des clés explicites

    Args:
        filename (str): nom de fichier

    Returns:
        dict: dictionnaire de données EXIF avec des clés explicites
    """
    img = PIL.Image.open(filename)
    exif_dico = img._getexif()

    exif_c = {TAGS[clé]: valeur for clé, valeur in exif_dico.items()}

    gps = exif_c["GPSInfo"]
    exif_c["GPSInfo"] = {GPSTAGS[clé]: valeur for clé, valeur in gps.items()}

    return exif_c


print("Données EXIF claires de la photo :")
affiche_dico(donnees_exif("image_mystere.jpg"))

Données EXIF claires de la photo :
GPSInfo :	{'GPSVersionID': b'\x02\x02\x00\x00', 'GPSLatitudeRef': 'N', 'GPSLatitude': (48.0, 50.4225, 0.0), 'GPSLongitudeRef': 'E', 'GPSLongitude': (2.0, 18.899, 0.0), 'GPSAltitude': 55.2454}
ResolutionUnit :	2
ExifOffset :	228
Make  :	NIKON CORPORATION
Model :	NIKON D7200
Software :	Adobe Photoshop Lightroom 6.8 (Windows)
DateTime :	2017:02:06 03:10:48
XResolution :	300.0
YResolution :	300.0
ExifVersion :	b'0230'
ShutterSpeedValue :	8.965784
ApertureValue :	3.851999
DateTimeOriginal :	2015:11:30 16:26:55
DateTimeDigitized :	2015:11:30 16:26:55
ExposureBiasValue :	-0.3333333333333333
MaxApertureValue :	3.8
MeteringMode :	2
LightSource :	0
Flash :	16
FocalLength :	22.0
ColorSpace :	1
WhiteBalance :	0
DigitalZoomRatio :	1.0
FocalPlaneXResolution :	2558.6412048339844
FocalPlaneYResolution :	2558.6412048339844
FocalPlaneResolutionUnit :	3
SubsecTimeOriginal :	65
SubsecTimeDigitized :	65
Sharpness :	0
SubjectDistanceRange :	0
SensingMethod :	2
FileSource :

### Exercice n°12 : Chiffres romains

Dans l'écriture des chiffres romains, on utilise les lettres I, V, X, L, C, D et M, qui ont pour valeurs respectives 1, 5, 10, 50, 100, 500 et 1000.

Un nombre écrit en chiffres romains se lit de gauche à droite. En première approximation, sa valeur se détermine en faisant la somme des valeurs individuelles de chaque symbole, sauf quand l'un des symboles précède un symbole de valeur supérieure ; dans ce cas, on soustrait la valeur du premier symbole au deuxième.

1. Ecrire une fonction `romain_vers_decimal(nb : str) -> int` qui prend en argument une chaîne de caractères `nb` représentant un nombre écrit en chiffres romains et qui renvoie ce nombre en écriture décimale.


In [33]:
def romain_vers_decimal(nb: str) -> int:
    """convertit un nombre en chiffres romains en écriture décimale

    Args:
        nb (str): un nombre écrit en chiffres romains

    Returns:
        int: nb en écriture décimale
    """
    dico = {"M": 1000, "D": 500, "C": 100, "L": 50, "X": 10, "V": 5, "I": 1}
    valeur = 0
    for i in range(len(nb) - 1):
        if dico[nb[i]] < dico[nb[i + 1]]:
            valeur -= dico[nb[i]]
        else:
            valeur += dico[nb[i]]
    valeur += dico[nb[-1]]
    return valeur


assert romain_vers_decimal("I") == 1
assert romain_vers_decimal("V") == 5
assert romain_vers_decimal("X") == 10
assert romain_vers_decimal("XVIII") == 18
assert romain_vers_decimal("IX") == 9
assert romain_vers_decimal("DCLXVI") == 666
assert romain_vers_decimal("DIX") == 509

2. Ecrire une fonction `decimal_vers_romain(nb: int) -> str` qui prend en argument un entier (inférieur à $5000$) et qui renvoie une chaîne de caractères représentant la valeur de cet entier en chiffres romains.


In [34]:
def decimal_vers_romain(nb: int) -> str:
    """convertit un nombre en écriture décimale en chiffres romains

    Args:
        nb (int): un nombre en écriture décimale

    Returns:
        str: nb en chiffres romains
    """
    assert nb < 5000

    dico = {1000: "M", 500: "D", 100: "C", 50: "L", 10: "X", 5: "V", 1: "I"}
    resultat = ""
    for i in range(3, -1, -1):
        coeff = nb // 10**i
        nb %= 10**i
        if coeff <= 3:
            resultat += dico[10**i] * coeff
        elif coeff == 4:
            resultat += dico[10**i] + dico[5 * 10**i]
        elif coeff <= 8:
            resultat += dico[5 * 10**i] + dico[10**i] * (coeff - 5)
        elif coeff == 9:
            resultat += dico[10**i] + dico[10 ** (i + 1)]
    return resultat


assert decimal_vers_romain(1) == "I"
assert decimal_vers_romain(2) == "II"
assert decimal_vers_romain(3) == "III"
assert decimal_vers_romain(4) == "IV"
assert decimal_vers_romain(5) == "V"
assert decimal_vers_romain(6) == "VI"
assert decimal_vers_romain(7) == "VII"
assert decimal_vers_romain(8) == "VIII"
assert decimal_vers_romain(9) == "IX"
assert decimal_vers_romain(10) == "X"
assert decimal_vers_romain(18) == "XVIII"
assert decimal_vers_romain(666) == "DCLXVI"
assert decimal_vers_romain(509) == "DIX"